app.database.host=${DB_HOST}
app.database.port=${DB_PORT:3306}
app.database.name=${DB_NAME}
app.database.username=${DB_USERNAME}
app.database.password=${DB_PASSWORD}

app.vapid-public-key=${VAPID_PUBLIC_KEY:}
app.vapid-private-key=${VAPID_PRIVATE_KEY:}
app.vapid-subject=${VAPID_SUBJECT:mailto:admin@anphuc.xyz}

app.application-name=starter-kit
app.base-url=https://anphuc.xyz
app.allowed-origins=https://anphuc.xyz
app.login-page-url=${app.base-url}/auth/login
app.login-success-url=${app.base-url}/auth/login-success

app.s3.bucket-name=${S3_BUCKET_NAME}
app.s3.region=${S3_REGION:ap-southeast-1}
app.s3.access-key=
app.s3.secret-key=
app.s3.base-url=
app.s3.storage-class=STANDARD

app.admin-user-email=${ADMIN_EMAIL:admin@anphuc.xyz}
app.admin-user-password=${ADMIN_PASSWORD}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_OAUTH_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_OAUTH_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET:}

spring.datasource.url=jdbc:mysql://${app.database.host}:${app.database.port}/${app.database.name}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${app.database.username}
spring.datasource.password=${app.database.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=false

spring.mail.host=${SMTP_HOST:localhost}
spring.mail.port=${SMTP_PORT:1025}
spring.mail.username=${SMTP_USERNAME:user}
spring.mail.password=${SMTP_PASSWORD:password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080
server.forward-headers-strategy=FRAMEWORK
